#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: akka-rolling-update-demo
  name: akka-rolling-update-demo
spec:
  replicas: 3
  selector:
    matchLabels:
     app: akka-rolling-update-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: akka-rolling-update-demo
        actorSystemName: akka-rolling-update-demo
    spec:
      containers:
      - name: akka-rolling-update-demo
        image: integration-test-rolling-update-kubernetes:1.3.3.7
        # Remove for a real project, the image is picked up locally for the integration test
        imagePullPolicy: Never
        #health
        livenessProbe:
          httpGet:
            path: /alive
            port: management
        readinessProbe:
          httpGet:
            path: /ready
            port: management
        #health
        ports:
        # akka-management bootstrap
        - name: management
          containerPort: 8558
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # The pod deletion cost will use this var to identity the pod to be annotated (in case that applies)
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REQUIRED_CONTACT_POINT_NR
          value: "3"
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75 -Xlog:gc -Dakka.rolling-update.kubernetes.custom-resource.enabled=on"
#deployment
---
#rbac-reader
#
# Create a role, `pod-annotator`, that can list pods and
# bind the default service account in the namespace
# that the binding is deployed to to that role.
#

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"] # requires "patch" to annotate the pod
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
subjects:
  # Uses the default service account.
  # Consider creating a dedicated service account to run your
  # Akka Cluster services and binding the role to that one.
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
#rbac-reader
---
#rbac-podcost-cr
#
# Create a role, `podcost-access`, that can update the PodCost CR
#
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podcost-access
rules:
  - apiGroups: ["akka.io"]
    resources: ["podcosts"]
    verbs: ["get", "create", "update", "delete", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podcost-access
subjects:
  - kind: User
    name: system:serviceaccount:akka-rolling-update-demo-cr-ns:default
roleRef:
  kind: Role
  name: podcost-access
  apiGroup: rbac.authorization.k8s.io
#rbac-podcost-cr
